import { Open_Sans } from 'next/font/google';
import Link from 'next/link';

import './globals.css';

const sans = Open_Sans({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className={sans.className}>
      <body>
        <header>
          <Link href='/'>
            <h1>{"Ellie's Blog"}</h1>
          </Link>
          <nav>
            <Link href='/'>home</Link>
            <Link href='/about'>about</Link>
            <Link href='/posts'>posts</Link>
            <Link href='/contact'>contact</Link>
          </nav>
        </header>
        <main>{children}</main>
        <footer>
          {"Don't forget to CODE your DREAM | All Right Reserved"}
        </footer>
      </body>
    </html>
  );
}
